insert into public.exercises (name, primary_muscle, equipment) values
  ('Barbell Bench Press', 'Chest', 'Barbell'),
  ('Incline Barbell Bench Press', 'Chest', 'Barbell'),
  ('Dumbbell Bench Press', 'Chest', 'Dumbbell'),
  ('Incline Dumbbell Press', 'Chest', 'Dumbbell'),
  ('Cable Fly', 'Chest', 'Cable'),
  ('Push-up', 'Chest', 'Bodyweight'),
  ('Chest Dip', 'Chest', 'Bodyweight'),
  ('Pec Deck Machine', 'Chest', 'Machine'),
  ('Deadlift', 'Back', 'Barbell'),
  ('Barbell Row', 'Back', 'Barbell'),
  ('Pull-up', 'Back', 'Bodyweight'),
  ('Chin-up', 'Back', 'Bodyweight'),
  ('Lat Pulldown', 'Back', 'Cable'),
  ('Seated Cable Row', 'Back', 'Cable'),
  ('Dumbbell Row', 'Back', 'Dumbbell'),
  ('T-Bar Row', 'Back', 'Barbell'),
  ('Face Pull', 'Back', 'Cable'),
  ('Back Squat', 'Legs', 'Barbell'),
  ('Front Squat', 'Legs', 'Barbell'),
  ('Leg Press', 'Legs', 'Machine'),
  ('Romanian Deadlift', 'Legs', 'Barbell'),
  ('Walking Lunge', 'Legs', 'Dumbbell'),
  ('Bulgarian Split Squat', 'Legs', 'Dumbbell'),
  ('Leg Extension', 'Legs', 'Machine'),
  ('Leg Curl', 'Legs', 'Machine'),
  ('Standing Calf Raise', 'Legs', 'Machine'),
  ('Goblet Squat', 'Legs', 'Dumbbell'),
  ('Hip Thrust', 'Legs', 'Barbell'),
  ('Overhead Press', 'Shoulders', 'Barbell'),
  ('Seated Dumbbell Press', 'Shoulders', 'Dumbbell'),
  ('Arnold Press', 'Shoulders', 'Dumbbell'),
  ('Lateral Raise', 'Shoulders', 'Dumbbell'),
  ('Front Raise', 'Shoulders', 'Dumbbell'),
  ('Rear Delt Fly', 'Shoulders', 'Dumbbell'),
  ('Upright Row', 'Shoulders', 'Barbell'),
  ('Dumbbell Shrug', 'Shoulders', 'Dumbbell'),
  ('Barbell Curl', 'Arms', 'Barbell'),
  ('Dumbbell Curl', 'Arms', 'Dumbbell'),
  ('Hammer Curl', 'Arms', 'Dumbbell'),
  ('Preacher Curl', 'Arms', 'Barbell'),
  ('Concentration Curl', 'Arms', 'Dumbbell'),
  ('Tricep Pushdown', 'Arms', 'Cable'),
  ('Overhead Tricep Extension', 'Arms', 'Dumbbell'),
  ('Skull Crusher', 'Arms', 'Barbell'),
  ('Close-Grip Bench Press', 'Arms', 'Barbell'),
  ('Tricep Dip', 'Arms', 'Bodyweight'),
  ('Plank', 'Core', 'Bodyweight'),
  ('Hanging Leg Raise', 'Core', 'Bodyweight'),
  ('Cable Crunch', 'Core', 'Cable'),
  ('Russian Twist', 'Core', 'Bodyweight'),
  ('Ab Wheel Rollout', 'Core', 'Bodyweight'),
  ('Sit-up', 'Core', 'Bodyweight')
on conflict do nothing;
